import MovieDetail from './movie/MovieDetail'
import MovieForm from './movie/MovieForm'
import MovieImporter from './movie/MovieImporter'
import MovieList from './movie/MovieList'
import DirectorList from './director/DirectorList'
import DirectorForm from './director/DirectorForm'
import DirectorDetail from './director/DirectorDetail'
import ActorList from './actor/ActorList'
import ActorForm from './actor/ActorForm'
import ActorDetail from './actor/ActorDetail'
import GenreList from './genre/GenreList'
import UserList from './user/UserList'
import UserDetail from './user/UserDetail'

export { MovieDetail, MovieForm, MovieList, DirectorList, DirectorForm, DirectorDetail, ActorList, ActorForm, ActorDetail, GenreList, MovieImporter, UserList, UserDetail}